USE ROLE ACCOUNTADMIN;
USE DATABASE ADVENTUREWORKS;

-- Create storage integration to S3
CREATE OR REPLACE STORAGE INTEGRATION AWS_ADVENTUREWORKS
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<your-account>:role/adventureworks'
  ENABLED = TRUE
  STORAGE_ALLOWED_LOCATIONS = ('s3://adventureworks-<your-uniquifier>');
DESCRIBE INTEGRATION AWS_ADVENTUREWORKS;
GRANT USAGE ON INTEGRATION AWS_ADVENTUREWORKS TO ROLE SYSADMIN;

-- Run this to get STORAGE_AWS_IAM_USER_ARN & STORAGE_AWS_EXTERNAL_ID values
-- Add these values to Trust Relationship on role adventureworks in AWS
DESCRIBE INTEGRATION AWS_ADVENTUREWORKS;

-- Create stage
CREATE OR REPLACE STAGE AWS_ADVENTUREWORKS
  STORAGE_INTEGRATION = AWS_ADVENTUREWORKS
  URL = 's3://adventureworks-<your-uniquifier>';
GRANT USAGE ON STAGE AWS_ADVENTUREWORKS TO ROLE SYSADMIN;

LIST @AWS_ADVENTUREWORKS;


-- Create File Format
USE ROLE SYSADMIN;
USE DATABASE ADVENTUREWORKS;

CREATE OR REPLACE FILE FORMAT AW_CSV
COMPRESSION = 'NONE'
FIELD_DELIMITER = '|' --"csv" file is pipe delimited
RECORD_DELIMITER = '\n'
SKIP_HEADER = 0
TRIM_SPACE = TRUE
ENCODING = UTF16LE --This is important, UTF8 will fail
SKIP_BYTE_ORDER_MARK = TRUE --files start with BOM: ÿþ
;
