USE ROLE SYSADMIN;
USE DATABASE ADVENTUREWORKS;

-- Copy data from files into tables
COPY INTO DIMACCOUNT
FROM @AWS_ADVENTUREWORKS/DimAccount.csv
FILE_FORMAT = AW_CSV;

COPY INTO DIMCUSTOMER
FROM @AWS_ADVENTUREWORKS/DimCustomer.csv
FILE_FORMAT = AW_CSV;

COPY INTO DIMCURRENCY
FROM @AWS_ADVENTUREWORKS/DimCurrency.csv
FILE_FORMAT = AW_CSV;

COPY INTO DIMDATE
FROM @AWS_ADVENTUREWORKS/DimDate.csv
FILE_FORMAT = AW_CSV;

COPY INTO DIMDEPARTMENTGROUP
FROM @AWS_ADVENTUREWORKS/DimDepartmentGroup.csv
FILE_FORMAT = AW_CSV;

COPY INTO DIMEMPLOYEE
FROM @AWS_ADVENTUREWORKS/DimEmployee.csv
FILE_FORMAT = AW_CSV;

COPY INTO DIMGEOGRAPHY
FROM @AWS_ADVENTUREWORKS/DimGeography.csv
FILE_FORMAT = AW_CSV;

COPY INTO DIMORGANIZATION
FROM @AWS_ADVENTUREWORKS/DimOrganization.csv
FILE_FORMAT = AW_CSV;

COPY INTO DIMPRODUCT
FROM @AWS_ADVENTUREWORKS/DimProduct.csv
FILE_FORMAT = AW_CSV;

COPY INTO DIMPRODUCTCATEGORY
FROM @AWS_ADVENTUREWORKS/DimProductCategory.csv
FILE_FORMAT = AW_CSV;

COPY INTO DIMPRODUCTSUBCATEGORY
FROM @AWS_ADVENTUREWORKS/DimProductSubcategory.csv
FILE_FORMAT = AW_CSV;

COPY INTO DIMPROMOTION
FROM @AWS_ADVENTUREWORKS/DimPromotion.csv
FILE_FORMAT = AW_CSV;

COPY INTO DIMRESELLER
FROM @AWS_ADVENTUREWORKS/DimReseller.csv
FILE_FORMAT = AW_CSV;

COPY INTO DIMSALESREASON
FROM @AWS_ADVENTUREWORKS/DimSalesReason.csv
FILE_FORMAT = AW_CSV;

COPY INTO DIMSALESTERRITORY
FROM @AWS_ADVENTUREWORKS/DimSalesTerritory.csv
FILE_FORMAT = AW_CSV;

COPY INTO DIMSCENARIO
FROM @AWS_ADVENTUREWORKS/DimScenario.csv
FILE_FORMAT = AW_CSV;

COPY INTO FACTADDITIONALINTERNATIONALPRODUCTDESCRIPTION
FROM @AWS_ADVENTUREWORKS/FactAdditionalInternationalProductDescription.csv
FILE_FORMAT = AW_CSV;

COPY INTO FACTCALLCENTER
FROM @AWS_ADVENTUREWORKS/FactCallCenter.csv
FILE_FORMAT = AW_CSV;

COPY INTO FACTCURRENCYRATE
FROM @AWS_ADVENTUREWORKS/FactCurrencyRate.csv
FILE_FORMAT = AW_CSV;

COPY INTO FACTFINANCE
FROM @AWS_ADVENTUREWORKS/FactFinance.csv
FILE_FORMAT = AW_CSV;

COPY INTO FACTINTERNETSALES
FROM @AWS_ADVENTUREWORKS/FactInternetSales.csv
FILE_FORMAT = AW_CSV;

COPY INTO FACTINTERNETSALESREASON
FROM @AWS_ADVENTUREWORKS/FactInternetSalesReason.csv
FILE_FORMAT = AW_CSV;

COPY INTO FACTPRODUCTINVENTORY
FROM @AWS_ADVENTUREWORKS/FactProductInventory.csv
FILE_FORMAT = AW_CSV;

COPY INTO FACTRESELLERSALES
FROM @AWS_ADVENTUREWORKS/FactResellerSales.csv
FILE_FORMAT = AW_CSV;

COPY INTO FACTSALESQUOTA
FROM @AWS_ADVENTUREWORKS/FactSalesQuota.csv
FILE_FORMAT = AW_CSV;

COPY INTO FACTSURVEYRESPONSE
FROM @AWS_ADVENTUREWORKS/FactSurveyResponse.csv
FILE_FORMAT = AW_CSV;

COPY INTO NEWFACTCURRENCYRATE
FROM @AWS_ADVENTUREWORKS/NewFactCurrencyRate.csv
FILE_FORMAT = AW_CSV;

COPY INTO PROSPECTIVEBUYER
FROM @AWS_ADVENTUREWORKS/ProspectiveBuyer.csv
FILE_FORMAT = AW_CSV;
