-- Create Share
USE ROLE ACCOUNTADMIN;

CREATE SHARE ADVENTUREWORKS;

-- Grant Permissions
GRANT USAGE ON DATABASE ADVENTUREWORKS TO SHARE ADVENTUREWORKS;
GRANT USAGE ON SCHEMA ADVENTUREWORKS.PUBLIC TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.ADVENTUREWORKSDWBUILDVERSION TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.DIMACCOUNT TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.DIMCURRENCY TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.DIMCUSTOMER TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.DIMDATE TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.DIMDEPARTMENTGROUP TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.DIMEMPLOYEE TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.DIMGEOGRAPHY TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.DIMORGANIZATION TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.DIMPRODUCT TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.DIMPRODUCTCATEGORY TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.DIMPRODUCTSUBCATEGORY TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.DIMPROMOTION TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.DIMRESELLER TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.DIMSALESREASON TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.DIMSALESTERRITORY TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.DIMSCENARIO TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.FACTADDITIONALINTERNATIONALPRODUCTDESCRIPTION TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.FACTCALLCENTER TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.FACTCURRENCYRATE TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.FACTFINANCE TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.FACTINTERNETSALES TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.FACTINTERNETSALESREASON TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.FACTPRODUCTINVENTORY TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.FACTRESELLERSALES TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.FACTSALESQUOTA TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.FACTSURVEYRESPONSE TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.NEWFACTCURRENCYRATE TO SHARE ADVENTUREWORKS;
GRANT SELECT ON VIEW ADVENTUREWORKS.PUBLIC.PROSPECTIVEBUYER TO SHARE ADVENTUREWORKS;

-- Add Consumers
ALTER SHARE ADVENTUREWORKS ADD ACCOUNTS = <>;
